project:
  type: website
  output-dir: docs

website:
  title: "Connecting Survival Analysis and Infectious Disease Modeling"
  description: "Lorentz Center Workshop | 15–19 June 2026 | Leiden, the Netherlands"
  favicon: images/favicon.ico
  repo-url: https://github.com/kylieainslie/lorentz_center_workshop
  repo-actions: [issue]
  page-footer:
    center: "Lorentz Center Workshop, Leiden 2026 | [LORENTZCENTER.NL](https://www.lorentzcenter.nl)"
  navbar:
    background: "#003865"
    foreground: light
    title: "SA–IDM Workshop"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Programme"
        href: https://www.lorentzcenter.nl/connecting-survival-analysis-and-infectious-disease-modeling.html
      - text: "Preparation"
        href: preparation.qmd
      - text: "Case Study"
        href: case-studies.qmd
      - text: "Materials"
        menu:
          - text: "Day 1: Foundation Setting"
            href: day1.qmd
          - text: "Day 2: Methodological Exploration"
            href: day2.qmd
          - text: "Day 3: Integration & Refinement"
            href: day3.qmd
          - text: "Day 4: Knowledge Transfer Tools"
            href: day4.qmd
          - text: "Day 5: Consolidation & Future Directions"
            href: day5.qmd
          - text: "---"
          - text: "Vignettes"
            href: vignettes/index.qmd
      - text: "Contribute"
        menu:
          - text: "Group Analysis Scripts"
            href: analysis/index.qmd
          - text: "Vignettes"
            href: vignettes/index.qmd
      - text: "Organizers"
        href: organizers.qmd
    right:
      - icon: github
        href: https://github.com/kylieainslie/lorentz_center_workshop

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    page-layout: article
